kind: pipeline
name: default

steps:
  - name: build php docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ivanpopov/online-cource-empty
      dockerfile: docker/php/Dockerfile

  - name: install dependencies
    image: ivanpopov/online-cource-empty
    commands:
      - composer install
#
#volumes:
#  - name: dockersock
#    host:
#      path: /var/run/docker.sock
#kind: pipeline
#name: default
#
#steps:
#  - name: test
#    image: plugins/docker
##    volumes:
##      - name: dockersock
##        path: /var/run/docker.sock
#    commands:
#      - docker ps -a
#
#volumes:
#  - name: dockersock
#    host:
#      path: /var/run/docker.sock