kind: pipeline
name: default

steps:
  - name: build php docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ivanpopov/online-cource-empty
      target: prod
      dockerfile: docker/php/Dockerfile

  - name: simple check
    image: ivanpopov/online-cource-empty
    commands:
      - composer install
      - composer validate
      - vendor/bin/php-cs-fixer fix --dry-run
      - bin/console ca:cl
#---
#kind: pipeline
#type: exec
#name: default
#
#platform:
#  os: linux
#  arch: amd64
#
#steps:
#  - name: greeting
#    commands:
#      - echo hello world
#      - docker build --no-cache -t online_cource:${DRONE_COMMIT} -f docker/php/Dockerfile .

#
#volumes:
#  - name: dockersock
#    host:
#      path: /var/run/docker.sock
#kind: pipeline
#name: default
#
#steps:
#  - name: test
#    image: plugins/docker
##    volumes:
##      - name: dockersock
##        path: /var/run/docker.sock
#    commands:
#      - docker ps -a
#
#volumes:
#  - name: dockersock
#    host:
#      path: /var/run/docker.sock