version: '3.2'

services:
    php:
        build: docker/php
        volumes:
            - .:/var/www/html
            - ./docker/php/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini
            - trash:/var/www/
        entrypoint: ./docker/php/docker-entrypoint.sh
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
            - ./docker/nginx/symfony.conf:/etc/nginx/sites-available/symfony.conf
    db:
        image: postgres:12
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
#    mailer:
#        image: schickling/mailcatcher
#        ports:
#            - "1080:1080"
#    db_test:
#        image: postgres:10
#        ports:
#            - "5433:5432"
#        command: ["postgres", "-c", "fsync=off", "-c", "full_page_writes=off"]
#        environment:
#            - POSTGRES_DB
#            - POSTGRES_USER
#            - POSTGRES_PASSWORD
volumes:
    db:
    trash:
